spring.application.name=finance-tracker
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker?stringtype=unspecified
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mematikan restart otomatis (jika diperlukan)
spring.devtools.restart.enabled=true

# Menambah folder tambahan untuk dipantau
spring.devtools.restart.additional-paths=src/main/java

# Mengecualikan folder agar tidak memicu restart (hanya reload)
spring.devtools.restart.exclude=static/**,public/**

# JWT Configuration
jwt.secret=2XZCFnmx0gac6Obn7LVsXtxpT36eCKJBGEbXg3luFuN2
jwt.expiration=360000